package com.flipcard.constants;

public class SqlQueries {
	public static String GET_COURSES="SELECT * FROM CATALOG";
	public static String GET_COURSE_NAMES="SELECT COURSENAME FROM CATALOG";
	public static String GET_REGISTERED_COURSE_NAMES="SELECT COURSENAME FROM STUDENTCOURSES WHERE USERNAME=?";
	public static String CHECK_IDENTITY="SELECT ROLE FROM AUTHCREDENTIALS WHERE USERNAME=? AND PASSWORD=?";
	public static String VERIFY_COURSE="SELECT * FROM CATALOG WHERE COURSENAME=?";
	public static String ADD_NEW_COURSE="INSERT INTO STUDENTCOURSES VALUES (?,?,?,?)";
	public static String DROP_COURSE="DELETE FROM STUDENTCOURSES WHERE USERNAME=? AND COURSENAME=?";
	public static String ADD_COURSE_TO_TEACH="UPDATE CATALOG SET PROFESSORNAME=? WHERE COURSENAME=? AND PROFESSORNAME=?";
	public static String GET_TAUGHT_COURSE_NAMES="SELECT COURSENAME FROM CATALOG WHERE PROFESSORNAME=?";
	public static String GET_STUDENTS_NAME="SELECT USERNAME FROM STUDENTCOURSES WHERE COURSENAME=?";
	public static String GET_ALL_STUDENTS="SELECT * FROM STUDENT";
	public static String RECORD_GRADES="UPDATE STUDENTCOURSES SET GRADES=? WHERE COURSENAME=? AND USERNAME=?";
	public static String GET_REPORT_CARD="SELECT COURSENAME,GRADES FROM STUDENTCOURSES WHERE USERNAME=?";
	public static String ADD_USER_CREDENTIALS="INSERT INTO AUTHCREDENTIALS VALUES (?,?,?)";
	public static String ADD_STUDENT_INFO="INSERT INTO STUDENT VALUES (?,?,?,?,?,?)";
	public static String ADD_PROFESSOR_INFO="INSERT INTO PROFESSOR VALUES (?,?,?,?,?)";
	public static String ADD_ADMIN_INFO="INSERT INTO ADMIN VALUES (?,?,?,?)";
	public static String CHECK_USERNAME="SELECT * FROM AUTHCREDENTIALS WHERE USERNAME=?";
	public static String GET_USERS_WITH_ROLE="SELECT USERNAME FROM AUTHCREDENTIALS WHERE ROLE=?";
	public static String DELETE_USER_WITH_ROLE="DELETE FROM AUTHCREDENTIALS WHERE USERNAME=? and ROLE=?";
	public static String DELETE_STUDENT_INFO="DELETE FROM STUDENT WHERE USERNAME=?";
	public static String DELETE_PROFESSOR_INFO="DELETE FROM PROFESSOR WHERE USERNAME=?";
	public static String DELETE_STUDENT_COURSES="DELETE FROM STUDENTCOURSES WHERE USERNAME=?";
	public static String RESET_PROFESSOR_COURSES="UPDATE CATALOG SET PROFESSORNAME='' WHERE PROFESSORNAME=?";
	public static String DELETE_ADMIN_INFO="DELETE FROM ADMIN WHERE USERNAME=?";
	
}
